# -*- coding: utf-8 -*-
dna2rna_tasks = [
    "Generate a guide RNA for targeting the DNA sequence <dna>GCGAGGGTGTCAAAGGCCAGGTCCACATTGCAGTTGTTTTTAACCGAGGTCTCCACGAAGGCCATGCCCAGGGAGGCAGCTAGCTCCTCGGCCTCCTGGGCTGAGACACAGCGGGTGCTCTGCAGGTCACTCTTGTGGCCAACCAGCAGGAAGATGACCTTGTCCGGGCCCTGAGTGGCCATGACCTCCTGGTGCCAGTC</dna>.",
    "Design a guide RNA to complement the DNA sequence <dna>TCTAATATATCTTTCTCTTAAGGTGCTCACCCCTTTGAAGTGGTACCAGAGCATGATAAGACCACCAGTATGTAGACATTTTGTTCTTTATTCCCTGAAAATATTAGGCATGCATTTAAATTCCCATTTTAAGAAAATACCATGTGTACTCCACATACAGACACTAATGGGAAATTTAGTTTGTAAAAAATCATGTCTGTGTACACAGTTACAAATTTTTGCAAAGGAAAGATAAATACAATATTCCTATGGCCATAATGGCAAAGACAACACTGCTGCTTCTCTGGTTGGAGTCACGTGAGCCAATGGTAAACCTGCATCTCTGTTTCTCACCAGTACTCTTCCTATGGTTACGAGCCCATGGGTGGATGGCTGCACCACCAAATCATCCCCGTGGTGTCCCAACAGCACCCC</dna>.",
    "Determine which of <rna>GTCATGAGCTTCGTTAACAT</rna> or <rna>AGGACGGCGCGCCCGCGGAG</rna> has a greater editing efficiency for the DNA sequence <dna>CATGGCCGGCGACGACGACGAGGACGGCGCGCCCGCGGAGCGGCGCCTGGGCCGCGCCGACCTGGTCATGAGCTTCGTTAACATGGGTGAGTGCGGCCGCCCGCGCGGGGACCCTCGGAGTAAGCTGGCTGCAGGGGAGGGGCGCGCATCCGCGGGCTGTGCCGGGCCCTGGCCGAACGGGGAGTCACAGACGGTGGACG</dna>.",
]

dnapred_tasks = [
    "Does the given dna sequence <dna>TGAGGATCAGTGTGTTGATGCAATTTTTAAGAAACCCAGAGTCCTTCTATATAATGTTGCTGCCATCCCCCAGCTTCTCAGAGTTTTCTGTATCTAGCTGACTGGTGTGTGAAAAACAAATAGGAACTATAAATTACTGGAAGTTTTAAGGTCAGGCTTGCATGGGAGGGTCACTGCTTCTGTTTACATTCCACTGTCCAGAATTAGTTACACAGCCCAATATAAAAGGTAAGGAAGCTGGGAAACATAGGTTTCCTGGGTGCAAAGAGGAAAATAAGATGGTGAATATGTATCATTATC</dna> contain a promoter region?",
    "Is there a promoter sequence present in the DNA sequence <dna>TATAATAATAACGAAGATGAGACGACAGTCGACAAGAAAAGCACCAGCTGTCCCCGCCACATACAAGTATATGAGAAGGGGACGCGGGAGAGCGCCGCGGGGGACCGACGCGCTATTGAGGGGGATGGGTACAAGCGGGGCGGGGAGGCCGGAGCTTTATCCAGGCCAATGAATGGCCACTTGCGATGCCCAATTGCACCAAGCTTGGAGCGCACACTCAACCCCTTCCCCAGCGGTATGCCAAAATTCACCGTCTGAATGGCGTTGGTGCAGGTCGGTACAGAGCTCTCCTGCGCCGAG</dna>?",
    "Can you confirm if there is a promoter sequence within <dna>CCCTCTCCGGGCTGGGAGCTCCGGCCGAGCGGAGGCGCGACGGAGAGCACCAGCGCAGGGCAGAGAGCCCGGAGCGACCGGCCAGAGTAGGGCATCCGCTCGGGTGCTGCGGAGAACGAGGGCAGCTCCGAGCCGCCCCGGAGGACCGATGCGCCGGGTGGGGCGCTGGCCCCGAGGGCGTGAGCCGTCCGCAGATTGAGCAACTTGGGAACGGGCGGGCGGAGCGCAGGCGAGCCGGGCGCCCAGGACAGTCCCGCAGCGGGCGGGTGAGCGGGCCGCGCCCTCGCCCCTCCCGGGCCT</dna>?"
    "Examine whether the DNA sequence <dna>CATCCACATTCTGCGGGAGGCCACAAGAGCAGGGCCAACGTTAGAAAGGCCGCAAGGGGAGAGGAGGAGCCTGAGAAGCGCCAAGCACCTCCTCCGCTCTG</dna> contains a TFBS.",
    "Is there a TFBS in the DNA sequence <dna>AGGTCTGGCCTTTGGTCTCTCTCTGGGGAGCTCCTGCTTTGGGCTGGGCCCTGCAGGGGAGGCCGGGCGCTCCACTGGACCCTGCATGCAGCCTGCCAGCG</dna>?",
]

small_mole_tasks = [
    "I'm looking for the IUPAC name of <mol>Cc1cc(C)c(S(=O)(=O)Nc2ccc(F)c(N+[O-])c2)c(C)c1</mol>.",
    "What's the IUPAC designation of <mol>CCOc1cc(/C=C(\C#N)c2nc3ccccc3[nH]2)cc(Cl)c1OCc1ccc(Cl)cc1</mol>?",
    "How is the compound from <mol>COCC(C)n1c(C)cc(/C=C(\C#N)C(=O)NCCN2CCN(c3ncccn3)CC2)c1C</mol> notated in IUPAC terms?",
    "Can you decode the SMILES from this 3-ethyl-1-[(4-methoxy-6-methylpyridin-2-yl)methyl]-7-methyl-1,4-diazepane structure?",
]

protein_tasks = [
    "Please produce a protein sequence that exhibits stability.",
    "Generate a soluble protein sequence.",
    "Please create a protein sequence that ensures insolubility.",
    "Can you illustrate the genetic function of the <protein>MSLVSDLINLNLSDSTDKIIAEYIWVGGSGMDMRSKARTLPGPVTDPSQLPKWNYDGSSTGQAPGEDSEVILYPQAIFKDPFRRGNNILVMCDAYTPAGEPIPTNKRHAAAKVFSNPDVAAEVPWYGIEQEYTLLQKDVKWPVGWPIGGYPGPQGPYYCGIGADKSFGRDVVDSHYKACLYAGINISGINGEVMPGQWEFQVGPAVGISAADEIWVARYILERITEIAGVVVSFDPKPIPGDWNGAGAHCNYSTKSMREEGGYEIIKKAIDKLGLRHKEHIAAYGEGNERRLTGHHETADINTFLWGVANRGASIRVGRDTEKEGKGYFEDRRPASNMDPYIVTSMIAETTILWNP</protein> protein?",
    "How would you define the gene function of the <protein>MEDEAHEFFHTSDFAVDDLLVDFSNDDDEENDVVADSTTTTTITDSSNFSAADLPSFHGDVQDGTSFSGDLCIPSDDLADELEWLSNIVDESLSPEDVHKLELISGFKSRPDPKSDTGSPENPNSSSPIFTTDVSVPAKARSKRSRAAACNWASRGLLKETFYDSPFTGETILSSQQHLSPPTSPPLLMAPLGKKQAVDGGHRRKKDVSSPESGGAEERRCLHCATDKTPQWRTGPMGPKTLCNACGVRYKSGRLVPEYRPAASPTFVLAKHSNSHRKVMELRRQKEMSRAHHEFIHHHHGTDTAMIFDVSSDGDDYLIHHNVGPDFRQLI</protein> protein?",
    "Could you describe the function that the <protein>MSSTTTDSTELQNLIKLFQNCQTHPRQHFPAKSSAVLVCLYQEQREDKNELRVILTKRSTTLSSHPGEVALPGGKRDQEDKDDIATALREAREEIGLDPSLVTIISVLEPFVNKKGMSVAPVIGFLHDKKAFKQLPNPAEVEEIFDVPLEMFLKKQASRGTRA</protein> protein's gene performs?",
]

material_tasks = [
    "Generate a material that contains Li, Fe, Co, O",
    "Assemble a substance with Mg, Cr, O",
    "Construct the composition for a material with a required  bulk modulus of 0 GPa.",
    "Assemble the composition details for a material with a specified bulk modulus of 100 GPa.",
    "Generate the composition corresponding to a required  bulk modulus of 200 GPa.",
]
