# -*- coding: utf-8 -*-
dna2rna_tasks = [
    "Generate a guide RNA for targeting the DNA sequence <dna>GCGAGGGTGTCAAAGGCCAGGTCCACATTGCAGTTGTTTTTAACCGAGGTCTCCACGAAGGCCATGCCCAGGGAGGCAGCTAGCTCCTCGGCCTCCTGGGCTGAGACACAGCGGGTGCTCTGCAGGTCACTCTTGTGGCCAACCAGCAGGAAGATGACCTTGTCCGGGCCCTGAGTGGCCATGACCTCCTGGTGCCAGTC</dna>.",
    "Design a guide RNA to complement the DNA sequence <dna>TCTAATATATCTTTCTCTTAAGGTGCTCACCCCTTTGAAGTGGTACCAGAGCATGATAAGACCACCAGTATGTAGACATTTTGTTCTTTATTCCCTGAAAATATTAGGCATGCATTTAAATTCCCATTTTAAGAAAATACCATGTGTACTCCACATACAGACACTAATGGGAAATTTAGTTTGTAAAAAATCATGTCTGTGTACACAGTTACAAATTTTTGCAAAGGAAAGATAAATACAATATTCCTATGGCCATAATGGCAAAGACAACACTGCTGCTTCTCTGGTTGGAGTCACGTGAGCCAATGGTAAACCTGCATCTCTGTTTCTCACCAGTACTCTTCCTATGGTTACGAGCCCATGGGTGGATGGCTGCACCACCAAATCATCCCCGTGGTGTCCCAACAGCACCCC</dna>.",
    "Determine which of <rna>GTCATGAGCTTCGTTAACAT</rna> or <rna>AGGACGGCGCGCCCGCGGAG</rna> has a greater editing efficiency for the DNA sequence <dna>CATGGCCGGCGACGACGACGAGGACGGCGCGCCCGCGGAGCGGCGCCTGGGCCGCGCCGACCTGGTCATGAGCTTCGTTAACATGGGTGAGTGCGGCCGCCCGCGCGGGGACCCTCGGAGTAAGCTGGCTGCAGGGGAGGGGCGCGCATCCGCGGGCTGTGCCGGGCCCTGGCCGAACGGGGAGTCACAGACGGTGGACG</dna>.",
]

dnapred_tasks = [
    "Does the given dna sequence <dna>TGAGGATCAGTGTGTTGATGCAATTTTTAAGAAACCCAGAGTCCTTCTATATAATGTTGCTGCCATCCCCCAGCTTCTCAGAGTTTTCTGTATCTAGCTGACTGGTGTGTGAAAAACAAATAGGAACTATAAATTACTGGAAGTTTTAAGGTCAGGCTTGCATGGGAGGGTCACTGCTTCTGTTTACATTCCACTGTCCAGAATTAGTTACACAGCCCAATATAAAAGGTAAGGAAGCTGGGAAACATAGGTTTCCTGGGTGCAAAGAGGAAAATAAGATGGTGAATATGTATCATTATC</dna> contain a promoter region?",
    "Is there a promoter sequence present in the DNA sequence <dna>TATAATAATAACGAAGATGAGACGACAGTCGACAAGAAAAGCACCAGCTGTCCCCGCCACATACAAGTATATGAGAAGGGGACGCGGGAGAGCGCCGCGGGGGACCGACGCGCTATTGAGGGGGATGGGTACAAGCGGGGCGGGGAGGCCGGAGCTTTATCCAGGCCAATGAATGGCCACTTGCGATGCCCAATTGCACCAAGCTTGGAGCGCACACTCAACCCCTTCCCCAGCGGTATGCCAAAATTCACCGTCTGAATGGCGTTGGTGCAGGTCGGTACAGAGCTCTCCTGCGCCGAG</dna>?",
    "Can you confirm if there is a promoter sequence within <dna>CCCTCTCCGGGCTGGGAGCTCCGGCCGAGCGGAGGCGCGACGGAGAGCACCAGCGCAGGGCAGAGAGCCCGGAGCGACCGGCCAGAGTAGGGCATCCGCTCGGGTGCTGCGGAGAACGAGGGCAGCTCCGAGCCGCCCCGGAGGACCGATGCGCCGGGTGGGGCGCTGGCCCCGAGGGCGTGAGCCGTCCGCAGATTGAGCAACTTGGGAACGGGCGGGCGGAGCGCAGGCGAGCCGGGCGCCCAGGACAGTCCCGCAGCGGGCGGGTGAGCGGGCCGCGCCCTCGCCCCTCCCGGGCCT</dna>?"
    "Examine whether the DNA sequence <dna>CATCCACATTCTGCGGGAGGCCACAAGAGCAGGGCCAACGTTAGAAAGGCCGCAAGGGGAGAGGAGGAGCCTGAGAAGCGCCAAGCACCTCCTCCGCTCTG</dna> contains a TFBS.",
    "Is there a TFBS in the DNA sequence <dna>AGGTCTGGCCTTTGGTCTCTCTCTGGGGAGCTCCTGCTTTGGGCTGGGCCCTGCAGGGGAGGCCGGGCGCTCCACTGGACCCTGCATGCAGCCTGCCAGCG</dna>?",
]

small_mole_tasks = [
    "I'm looking for the IUPAC name of <mol>Cc1cc(C)c(S(=O)(=O)Nc2ccc(F)c(N+[O-])c2)c(C)c1</mol>.",
    "What's the IUPAC designation of <mol>CCOc1cc(/C=C(\C#N)c2nc3ccccc3[nH]2)cc(Cl)c1OCc1ccc(Cl)cc1</mol>?",
    "How is the compound from <mol>COCC(C)n1c(C)cc(/C=C(\C#N)C(=O)NCCN2CCN(c3ncccn3)CC2)c1C</mol> notated in IUPAC terms?",
    "Can you decode the SMILES from this 3-ethyl-1-[(4-methoxy-6-methylpyridin-2-yl)methyl]-7-methyl-1,4-diazepane structure?",
]
