# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    conda env revmoe -n sfm
    conda env create -f ./install/py39-torch2.2.2-cuda12.1.yaml -n sfm
    eval "$(conda shell.bash hook)"
    conda activate sfm
    pip install pytest
    pip install -e .
    pytest tests/
  displayName: 'Install and run unit tests'
