logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /data/xinwei/blob/sfmstoragewestus/psm
  timeout-sec: 120
  max-size-mb: 51200

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: sfmstoragewestus
  endpoint: https://sfmstoragewestus.blob.core.windows.net
  mode: azcli
  container: psm # Refer ./setup/baseConfig.yaml for full set of config parameters
