
description: train stageC:all  use progpt_inst_no_design

env_defaults:
  NODES: 1
  GPUS: 8
  WANDB_API_KEY:  "local-84c43c09161e2c012c3317ccb9becc6148001b8e"


target:
  service: aml
  # name: msrresrchvc
  name: sfm-nd96amsra100v4-uksouth
  # name: sfm-nc96-westus3

# target:
#   service: sing
#   name: baltic02
#   workspace_name: sfm-ws
environment:
  image: yaosen/sfm-py39-torch2.2.2-cuda12.1:20240417_a
  registry: msroctocr.azurecr.io
  username: msroctocr
# environment:
#   image: pj/mfmds:20230207_b
#   registry: itpeus4cr.azurecr.io
#   username: itpeus4cr

storage:
  hai1:
    storage_account_name: hai1data # Storage account
    container_name: mfm # Container name
    mount_dir: /hai1
  hai1sfm:
    storage_account_name: hai1data # Storage account
    container_name: sfm # Container name
    mount_dir: /hai1.sfm
  blob:
    storage_account_name: msralaphilly2
    container_name: ml-la
    mount_dir: /blob

code:
  local_dir: .

jobs:
- name: ft_bfm_adapter_with_progpt_train_bpe_inst
  tags:
  - 'ProjectID: GZK-0430-A40'
  sku: ${NODES}xG${GPUS}-A100
  mpi: true
  process_count_per_node: 1
  command:
  - mkdir -p /blob/v-zekunguo/nlm/checkpoints/bfm_scigpt_prot/stageC1e5
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export WANDB_PROJECT=sfm_test
  - export save_dir=/blob/v-zekunguo/nlm/checkpoints/bfm_scigpt_prot/stageC1e5
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install -e . --no-deps
  - bash scripts/progpt/ft_bfm_llama_prot_stageC.sh
  submit_args:
    container_args:
      shm_size: 1024g
