defaults:
- config_psm_schema
- backbone_config: graphormer
# - schedule: polynomial #'cosine', 'reduce_on_plateau','polynomial'
# - data_module: default
- _self_

model_type: psm
num_classes: 1
encoder_attention_heads: 32
encoder_ffn_embed_dim: 3072
encoder_embed_dim: 768
encoder_layers: 12
num_pred_attn_layer: 12
num_3d_bias_kernel: 32
max_length: 384
pbc_expanded_token_cutoff: 512
pbc_expanded_num_cell_per_direction: 5
multi_hop_max_dist: 5
droppath_prob: 0.0
act_dropout: 0.1
attn_dropout: 0.1
dropout: 0.1
sandwich_ln: true
noise_scale: 0.2
mask_ratio: 0.0
d_tilde: 1.0
pbc_cutoff: 40.0
data_path: ../msadata
dataset_names: ''
loadcheck_path: '/psm/sfmexpresults/xinwei/MSAGen/MSAGen_85M-20250313-lr4e-5-bsz4_2-steps2000000-warm1000/global_step18368/mp_rank_00_model_states.pt'
add_3d: false
no_2d: false
ft: false
infer: false
use_pbc: false
transformer_m_pretrain: true
mode_prob: 0.0,1.0,0.0
num_timesteps: 5000
num_timesteps_stepsize: -1
ddpm_beta_start: 1.0e-07
ddpm_beta_end: 0.006
ddpm_schedule: sigmoid
noise_mode: diff
num_edges: 25600
num_atom_features: 5120
attention_dropout: 0.0
share_encoder_input_output_embed: false
encoder_learned_pos: false
no_token_positional_embeddings: false
num_segments: 2
sentence_class_num: 2
sent_loss: false
apply_bert_init: false
activation_fn: relu
pooler_activation_fn: tanh
encoder_normalize_before: false
atom_loss_coeff: 1.0
pos_loss_coeff: 1.0
y_2d_loss_coeff: 1.0
max_positions: 512
num_atoms: 4608
num_in_degree: 512
num_out_degree: 512
num_spatial: 512
num_edge_dis: 128
edge_type: multi_hop
layerdrop: 0.0
apply_graphormer_init: true
pre_layernorm: false
seq_masking_method: transformerM
add_rope: true
rope_theta: 10000
num_residues: 32
max_num_aa: 1024
num_structure_encoder_layer: 4
encoder_pair_embed_dim: 64
structure_ffn_dim: 2028
structure_hidden_dim: 512
decoder_ffn_dim: 768
decoder_hidden_dim: 768
task: mae
sample_mode: false
train_data_path: ''
valid_data_path: ''
data_path_list: protein_msa_40_0.1_3k.lmdb
dataset_name_list: msageneration
dataset_split_raito: '1.0'
dataset_micro_batch_size: '2'
lamb_pde: 0.01
pbc_expanded_distance_cutoff: 20.0
pbc_use_local_attention: true
pbc_multigraph_cutoff: 7.0
diff_init_lattice_size_factor: 2.859496852322873
diff_init_lattice_size: 10.0
use_fixed_init_lattice_size: false
add_unit_cell_virtual_node: false
use_ddpm_for_material: false
crop_radius: 50.0
ligand_crop_size: 20.0
max_residue_num: 384
complex_mode_prob: 1.0,0.0,0.0,0.0
sample_ligand_only: false
plddt_threshold: 60.0
all_atom: false
molecule_ref_energy_source: PubChemQC-B3LYP-PM6/wb97xd3/1.0.0/train
molecule_outlier_energy_atoms: ''
diffusion_sampling: ddpm
diffusion_mode: edm
diffusion_noise_std: 1.0
use_adaptive_noise_std_for_periodic: false
periodic_diffusion_noise_std_factor: 1.0531306506190654
periodic_lattice_diffusion_noise_std: 0.5
diffusion_rescale_coeff: 1.0
ddim_eta: 0.0
ddim_steps: 50
clean_sample_ratio: 0.0
diffusion_training_loss: L2
diffusion_time_step_encoder_type: POSITIONAL
align_x0_in_diffusion_loss: true
separate_noise_head: false
psm_finetuneRL_mode: true
diffusion_sampling_rl: ddpm
num_timesteps_stepsize_rl: -1
reward_model: lddt
psm_value_step: 1
perturbation_each_traj: 2
reward_weight: 10.0
kl_weight: 0.1
ratio_clip: 0.0001
edm_P_mean: -1.2
edm_P_std: 1.5
edm_sigma_data: 16.0
edm_sample_num_steps: 200
edm_sample_sigma_min: 0.0004
edm_sample_sigma_max: 160.0
edm_sample_rho: 7.0
edm_sample_S_churn: 0.0
edm_sample_S_min: 0.0
edm_sample_S_max: 100.0
edm_sample_S_noise: 1.0
edm_x_init_treatment_from: ve
af3_sample_gamma_0: 0.8
af3_sample_gamma_min: 1.0
af3_sample_step_scale: 1.5
noise_embedding: fourier
force_loss_type: L1
force_head_type: MLP
node_type_edge_method: NON_EXCHANGABLE
stress_loss_type: L1
stress_loss_factor: 0.1
equivar_vec_init: RELATIVE_POS_VEC_BIAS
equivar_use_linear_bias: false
equivar_use_attention_bias: false
use_smooth_softmax: false
use_no_pre_cutoff_softmax: false
smooth_factor: 20.0
use_smooth_equviariant_norm: true
no_rotary_embedding_for_vector: false
mlm_from_decoder_feature: false
disable_data_aug: false
use_fp32_in_decoder: false
use_2d_atom_features: true
use_2d_bond_features: false
use_graphormer_path_edge_feature: true
preprocess_2d_bond_features_with_cuda: true
share_attention_bias: false
use_memory_efficient_attention: false
rescale_loss_with_std: true
material_force_loss_ratio: 0.5
material_energy_loss_ratio: 0.1
molecule_force_loss_ratio: 0.5
molecule_energy_loss_ratio: 0.1
energy_per_atom_label_scale: 1.0
molecule_energy_per_atom_std_override: 1.0
decoder_feat4energy: false
encoderfeat4noise: false
encoderfeat4mlm: true
AutoGradForce: false
supervise_force_from_head_when_autograd: false
supervise_autograd_stress: false
NoisePredForce: false
seq_only: false
freeze_backbone: false
hard_dist_loss_raito: 1.0
use_hard_dist_loss: false
use_bond_loss: false
if_total_energy: false
group_optimizer: false
group_lr_ratio: 1.0
num_force_and_noise_head_layers: 2
psm_validation_mode: true
sample_in_validation: false
num_sampling_time: 1
sampled_structure_output_path: null
psm_finetune_mode: true
psm_sample_structure_in_finetune: false
psm_finetune_reset_head: false
psm_finetune_noise_mode: diffusion
psm_finetune_valid_noise_mode: diffusion
psm_finetune_skip_ori_head: false
only_use_rotary_embedding_for_protein: true
psm_validate_for_train_set: false
algorithm_type: dpmsolver++
solver_order: 2
solver_type: midpoint
psm_matbench_task_name: ''
psm_matbench_fold_id: 0
use_dali_pipeline: false
relax_after_sampling_structure: false
structure_relax_step_size: 0.01
use_autograd_force_for_relaxation_and_md: false
relax_ase_steps: 8000
relax_initial_cell_matrix: 1,1,1
relax_lower_deformation: 0
relax_upper_deformation: 0
relax_deformation_step: 5
relax_fmax: 0.01
seed: 20921
total_num_steps: 2000000
total_num_epochs: 1000
max_tokens: 2048
train_batch_size: 1024
val_batch_size: 1024
val_batch_interval: 0
val_batch_log_interval: 1000
val_batch_log_all_metric: false
val_epoch_interval: 1
freeze_param_list: ''
unfreeze_param_list: ''
reset_act_each_step: false
use_unified_batch_sampler: true
activation_checkpoint_interval: 0
checkpointable_layers: null
gradient_clipping: 1.0
strategy: Zero1
pp_partition_layer_name: ''
pp_part_list: null
cpu: false
save_dir: /psm/sfmexpresults/xinwei/MSAGen/MSAGen_test-20250311-lr4e-5-bsz1_8-steps2000000-warm1000
save_batch_interval: 2000
save_epoch_interval: 1
log_interval: 20
finetune_from_checkpoint_dir: null
finetune_from_checkpoint_id: null
ifresume: false
load_ckpt: false
max_lr: 4.0e-05
init_lr: 8.0e-05
min_lr: 8.0e-06
weight_decay: 0.0
beta1: 0.9
beta2: 0.999
eps: 1.0e-08
warmup_num_steps: 1000
warmup_factor: 0.06
warmup_lr: 1.0e-06
warmup_num_epochs: 10
gradient_accumulation_steps: 8
fp16: false
auto_cast: false
grad_scaler_init: 1.0
bf16: false
fp8: false
mm_tensorcore: tf32
compile: false
zero_offload: false
zero_offload_dir: ./
find_unused_parameters: true
dynamic_loader: false
ifstack: false
unified_data_num_workers: 1
wandb: true
wandb_team: ai4s-sfm
wandb_group: msagen
wandb_project: MSAGen
wandb_run_name: 'infer'
early_stopping: false
early_stopping_patience: 10
early_stopping_metric: valid_loss
early_stopping_mode: min
calculate_metrics: false
profiling: false
prof_dir: ./prof
ptensorboard: false
allreduce_log_path: /tmp/stragglers
debug: false
local_rank: 0
world_size: 1
node_rank: 0
rank: 0
pipeline_model_parallel_size: 0
tensor_model_parallel_size: 1
deepspeed_config_path: ''
deepspeed_config: ''
dist_backend: nccl
backbone_config:
  model_type: graphormer
backbone: exp3
ode_mode: false
finetune_module: null
