description: train 3d ar diff generator

env_defaults:
  NODES: 2
  GPUS: 8
  WANDB_API_KEY: "local-8904f1b2b7174cdb7c0bf0b8a2c3195c1889c537"
  NAME: 3dardiff_v0.1_base_mp_nomad_qmdb_ddp_noniggli_epoch50_warmup8000_lr1e-4_wd0.1_bs256


target:
  service: sing
  name: baltic02
  workspace_name: sfm-ws


environment:
  image: ai4s-sfm:20240429.081857
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn


storage:
  blob:
    storage_account_name: msralaphilly2 # Storage account
    container_name: ml-la # Container name
    mount_dir: /msralaphilly2/ml-la

code:
  local_dir: ../SFM_framework



jobs:
- name: ${NAME}
  sku: ${NODES}xG${GPUS}-IB
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFMV1_Alignment]
  mpi: true
  identity: managed
  process_count_per_node: 1
  command:
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export WANDB_BASE_URL="https://microsoft-research.wandb.io"
  - export WANDB_TEAM=ai4s-sfm
  - export WANDB_PROJECT=${NAME}
  #- export wandb_group=sfm-3dar-diff
  - export NCCL_DEBUG=INFO
  - export NAME=${NAME}
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - pip install -e . --no-deps
  - python setup_cython.py build_ext --inplace
  - pip install git+https://github.com/NVIDIA/TransformerEngine.git@v1.6
  - pip uninstall flash-attn -y
  - pip install ase pymatgen
  - bash scripts/threedimargen/train_diff.sh
  submit_args:
    env:
      SHARED_MEMORY_PERCENT: 1.0
      CUDA_LAUNCH_BLOCKING: 1
