description: pretrain_base_1T_G128

env_defaults:
  NODES: 4
  GPUS: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

target:
  service: sing
  name: baltic02
  workspace_name: sfm-ws


environment:
  image: ai4s-sfm:20240429.081857
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
  hai1:
    storage_account_name: sfmdataeastus2 # Storage account
    container_name: nlm # Container name
    mount_dir: /nlm

code:
  local_dir: ../SFM_framework

jobs:
- name: finetune_base_1T_G128
  sku: ${NODES}xG${GPUS}-IB
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFMV1]
  mpi: true
  process_count_per_node: 1
  identity: managed
  command:
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export WANDB_PROJECT=nlm_base1b_1T
  - export WANDB_TEAM=ai4s-sfm
  - export wandb_group=finetune_base_1T_G128
  - export NCCL_DEBUG=INFO
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - pip install -e . --no-deps
  - python setup_cython.py build_ext --inplace
  - pip install git+https://github.com/NVIDIA/TransformerEngine.git@v1.6
  - pip uninstall flash-attn -y
  - pip install ase
  - export train_batch_size=4096
  - export val_batch_size=4096
  - export gradient_accumulation_steps=256
  - export tensor_model_parallel_size=1
  - export pipeline_model_parallel_size=2
  - export total_num_steps=10000
  - export warmup_num_steps=1000
  - export max_lr=6e-5
  - export learnable_cutoff=32000
  - export load_ckpt=True
  - export unfreeze_param_list="lm_head.weight,word_embeddings.weight"
  - export train_data_path=/nlm/SFMData/pretrain/20240724/train_split_lmdb/
  - export valid_data_path=/nlm/SFMData/pretrain/20240724/valid_split_lmdb/
  - export dict_path=/nlm/mistral/Mistral-7B-v0.1/
  - export loadcheck_path=/nlm/mistral/Mistral-7B-v0.1/original/
  - export save_dir=/nlm/peiran/output/pretrain_base_7T_G32/
  - bash scripts/nlm/pretrain_base7b_1T.sh
  submit_args:
    env:
      SHARED_MEMORY_PERCENT: 1.0
