description: train_sci_gpt_7b

env_defaults:
  NODES: 1
  GPUS: 1
  WANDB_API_KEY:  "d34f864932245bbdf3a9396a1ebde883ad2068f3"


target:
    service: aml
    name: nd96trial
    # vc: hai1

environment:
  image: shufxi/mfmds:20230807
  registry: itpeus4cr.azurecr.io
  username: itpeus4cr

code:
  local_dir: .

storage:
    pfm:
        storage_account_name: hai1data # Storage account
        container_name: pfm # Container name
        mount_dir: /pfm
    hai1:
        storage_account_name: hai1data # Storage account
        container_name: mfm # Container name
        mount_dir: /hai1
    blob:
        storage_account_name: msralaphilly2
        container_name: ml-la
        mount_dir: /blob

jobs:
- name: bp_gen
  tags:
  - 'ProjectID: PRJ-0209-A40'
  sku: G1
  mpi: true
  process_count_per_node: 1
  command:
  - eval "$$(conda shell.bash hook)" && conda create -n sfm python=3.9 -y && conda activate sfm
  - bash ./install/install.sh
  - pip install -e .
  - bash ./scripts/scigpt/bp_gen.sh
  submit_args:
    container_args:
      shm_size: 1024g
