description: train_sci_gpt_7b

env_defaults:
  NODES: 1
  GPUS: 4
  WANDB_API_KEY:  "d34f864932245bbdf3a9396a1ebde883ad2068f3"


target:
    service: aml
    name: nc96trial
    # vc: hai1



environment:
  image: shufxi/mfmds:20230807
  registry: itpeus4cr.azurecr.io
  username: itpeus4cr


storage:
  blob:
    storage_account_name: hai1data # Storage account
    container_name: mfm # Container name
    mount_dir: /hai1

code:
  local_dir: .

jobs:
- name: train_sci_gpt_7b_stageB_A100
  tags:
  - 'ProjectID: PRJ-0209-A40'
  sku: ${NODES}xG${GPUS}
  mpi: true
  process_count_per_node: 1
  command:
  - curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
  - tar -xzf vscode_cli.tar.gz
  - ./code tunnel --name "nc96dbg" --accept-server-license-terms
  - mkdir -p /hai1/shufxi/scigpt/7b/stageB_A100
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export WANDB_PROJECT=scigpt
  - export model_type=scigpt_7b
  - export save_dir=/hai1/shufxi/scigpt/7b/stageB_A100
  - export loadcheck_path=/hai1/shufxi/scigpt/7b/stageA_2k/global_step7999
  - export save_batch_interval=200
  - bash ./install/install.sh
  - pip install -e .
  - bash scripts/scigpt/pretrain_scigpt_7b_stageB_A100_nc96.sh

  submit_args:
    container_args:
      shm_size: 1024g
