description: train_sci_gpt_7bv2_stageA

env_defaults:
  NODES: 1
  GPUS: 4
  WANDB_API_KEY:  "d34f864932245bbdf3a9396a1ebde883ad2068f3"


target:
    service: aml
    name: nd96trial #nc96trial
    # vc: hai1



environment:
  image: shufxi/mfmds:20230807
  registry: itpeus4cr.azurecr.io
  username: itpeus4cr


storage:
  blob:
    storage_account_name: hai1data # Storage account
    container_name: mfm # Container name
    mount_dir: /hai1

code:
  local_dir: .

jobs:
- name: train_sci_gpt_7bv2_stageA
  tags:
  - 'ProjectID: PRJ-0209-A40'
  sku: ${NODES}xG${GPUS}
  mpi: true
  process_count_per_node: 1
  command:
  - mkdir -p /hai1/shufxi/scigpt/7bv2/stageA
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export WANDB_PROJECT=scigpt
  - export save_dir=/hai1/shufxi/scigpt/7bv2/stageA
  - bash ./install/install.sh
  - pip install -e .
  - bash scripts/scigpt/pretrain_scigpt_7bv2_stageA.sh

  submit_args:
    container_args:
      shm_size: 1024g
