description: protein confidence model plddt finetune

env_defaults:
  SKU: 1xG8
  WANDB_API_KEY: "local-138548ae9c9a3b39646af8ae2c4c6d4e22c51385"


# target:
#   service: sing
#   name: msrresrchvc
#   workspace_name: sfm-ws

target:
  service: aml
  name: sfm-nd96amsra100v4-uksouth


environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
  blob:
    storage_account_name: sfmdata
    container_name: protein
    mount_dir: /blob
  sfm:
    storage_account_name: sfmarca100
    container_name: sfm
    mount_dir: /sfm

code:
  local_dir: $CONFIG_DIR/../../../../

jobs:
- name: psm-finetune-protein-confidence-model-plddt-eval
  identity: managed
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: $SKU
  mpi: true
  process_count_per_node: 1
  command:
  - export wandb_team=ai4s-sfm
  - export wandb_project=psm_VT_finetune
  - export wandb_group=protein_confidence_model_plddt_finetune
  - export wandb_run_name=PSM300M_VT-plddt-mini-rollout-500-PDB-$$(date -u +%Y%m%d.%H%M%S)
  - export wandb_key=${WANDB_API_KEY}
  - export finetune_module=plddt_confidence_head
  - export psm_finetune_noise_mode=T
  - export num_pred_attn_layer=4
  - export layers=22
  - export hidden_size=1024
  - export ffn_size=4096
  - export num_head=32
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.0
  - export attn_dropout=0.1
  - export act_dropout=0.1
  - export weight_decay=0.0
  - export droppath_prob=0.0
  - export mask_ratio=0.0
  - export mode_prob='0.0,1.0,0.0'
  - export d_tilde=0.2
  - export max_lr=1.0e-4
  - export strategy=Zero1
  - export pipeline_model_parallel_size=0
  - export total_num_steps=50000
  - export warmup_num_steps=100
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export max_tokens=16000
  - export max_length=512
  - export gradient_accumulation_steps=4
  - export log_interval=1
  - export data_path=/nfs2/psmdata/
  - export data_path_list='20240101_PDB_Training_Data' #'AFDB50-plddt70.lmdb'
  - export dataset_name_list='pdb' # 'afdb'
  - export dataset_split_raito='1.0'
  - export dataset_micro_batch_size=80
  - export fp16=False
  - export clean_sample_ratio=0.5
  - export use_unified_batch_sampler=True
  - export use_dali_pipeline=False
  - export loadcheck_path=/ckpt/sfmexpresults/peiran/psmv1_vt_v8/checkpoints/global_step389895/mp_rank_00_model_states.pt
  - export save_dir=/blob/sfmexpresults/yaosen/$$wandb_run_name
  - export save_batch_interval=50
  - export num_timesteps=5000
  - export num_timesteps_stepsize=-250
  - export psm_sample_structure_in_finetune=True
  - export freeze_backbone=True
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install nvidia-dali-cuda120
  - conda install bioconda::lddt
  - export mask_ratio=0.0
  - export mode_prob='0.0,1.0,0.0'
  - export max_length=2048
  - export psm_finetune_mode=True
  - export psm_validation_mode=True
  - export data_path="/casp/sfm/psm/cameo-subset-casp14-and-casp15-combined.lmdb"
  - export loadcheck_path="/blob/sfmexpresults/yaosen/PSM300M_VT-plddt-mini-rollout-500-PDB-20240710.125911/global_step600/mp_rank_00_model_states.pt"
  - export save_dir="/sfm/sfmexpresults/jianwei/PSM300M_VT-plddt-mini-rollout-500-PDB-20240710.125911/global_step600/prediction"
  - inpsh="./scripts/psm/pretrain_psm_vanillatransformer.sh"
  - outsh="./scripts/psm/evaluate_psm_vanillatransformer_protein.sh"
  - cp $$inpsh $$outsh
  - sed -i 's/pretrain_psm.py/evaluate_psm_protein.py/' $$outsh
  - sed -i 's/seed=12345/seed=12345 finetune_module=plddt_confidence_head/' $$outsh
  - sed -i 's/seed=12345/seed=12345 psm_finetune_valid_noise_mode=T/' $$outsh
  - sed -i 's/seed=12345/seed=12345 max_model_num=1/' $$outsh
  - mkdir -p $$save_dir
  - bash $$outsh && rm $$outsh
  submit_args:
    container_args:
      shm_size: 1024g
  priority: High
  sla_tier: Premium
