name: sfm
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - biopython=1.83
  - dm-tree
  - loguru
  - mendeleev
  - networkx
  - ogb
  - peft
  - pybind11
  - python-lmdb
  - rdkit=2024.03.1
  - sentencepiece
  - setuptools-scm
  - tensorboard
  - transformers=4.40.1
  - wandb
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch=2.2.2=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch::torchaudio=2.2.2=py311_cu121
  - pytorch::torchvision=0.17.2=py311_cu121
  - pyg::pyg=2.5.2
  - pyg::pytorch-cluster=1.6.3
  - pyg::pytorch-scatter=2.1.2
  - pyg::pytorch-sparse=0.6.18
  - pyg::pytorch-spline-conv=1.2.2
  - defaults::cython
  - pip:
      - deepspeed==0.14.0
      - sacremoses==0.1.1
      - torch-tb-profiler==0.4.3
      - flash-attn==2.5.7
      - megablocks[gg]==0.5.1
      - hydra-core
      - e3nn
      - git+https://github.com/Open-Catalyst-Project/ocp.git
