 # Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV1

env_defaults:
  NODES: 2
  GPUS: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

# target:
#   service: sing
#   name: baltic02
#   workspace_name: msrresrchws

target:
  service: aml
  name: townsend1

environment:
  image: ai4s-sfm:20240531.170731
  registry: msroctocr.azurecr.io
  username: msroctocr

storage:
  blob:
    storage_account_name: sfmarca100 # Storage account
    container_name: sfm # Container name
    mount_dir: /sfm
    # storage_account_name: sfmdataeastus2 # Storage account
    # container_name: psm # Container name
    # mount_dir: /psm

code:
  local_dir: ../SFM_framework

jobs:
- name: psmv1_vt_v9_stage0
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS}-IB
  mpi: true
  process_count_per_node: 1
  command:
  - export WANDB_TEAM=ai4s-sfm
  - export wandb_group=psm_VT
  - export wandb_project=psm_VT
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - mkdir /blob/pfmexp/output
  - mkdir /blob/experiment/psm/psmv1_vt_v9_stage0
  - mkdir /blob/experiment/psm/psmv1_vt_v9_stage0/checkpoints
  - mkdir ./output
  - export path=run.sh
  - export num_pred_attn_layer=4
  - export layers=34
  - export hidden_size=1536
  - export ffn_size=6144
  - export num_head=32
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.0
  - export attn_dropout=0.1
  - export act_dropout=0.1
  - export weight_decay=0.0
  - export droppath_prob=0.0
  - export mask_ratio=0.6
  - export d_tilde=1.0
  - export max_lr=1.0e-4
  - export strategy=Zero1
  - export pipeline_model_parallel_size=0
  - export total_num_steps=500000
  - export warmup_num_steps=20000
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export max_tokens=16000
  - export max_length=1536
  - export gradient_accumulation_steps=8
  - export log_interval=100
  - export data_path=/nfs6/psmdata/
  # - export data_path=/psm/data/
  - export data_path_list='ur50_23_bpe_pack1536.lmdb'
  - export dataset_name_list='ur50'
  - export dataset_split_raito='1.0'
  - export dataset_micro_batch_size='16'
  - export fp16=True
  - export clean_sample_ratio=0.5
  - export num_timesteps=1000
  - export energy_loss_ratio=0.01
  - export force_loss_ratio=0.01
  - export ddpm_beta_start=1e-4
  - export ddpm_beta_end=2e-2
  - export use_unified_batch_sampler=True
  - export use_dali_pipeline=False
  - export loadcheck_path=/sfm/sfmexpresults/peiran/psmv1_vt_v9_stage0/checkpoints
  - export save_dir=/sfm/sfmexpresults/peiran/psmv1_vt_v9_stage0/checkpoints
  # - export loadcheck_path=/psm/exp/peiran/psmv1_vt_v5/checkpoints
  # - export save_dir=/psm/exp/peiran/psmv1_vt_v5/checkpoints
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install nvidia-dali-cuda120
  - bash ./scripts/psm/pretrain_psm_vanillatransformer_stage0.sh
  submit_args:
    container_args:
      shm_size: 1024g
  preemptible: false
