# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# train a chemical generalist

description: psm

env_defaults:
  NODES: 16
  GPUS_PER_NODE: 8
  WANDB_API_KEY: ${WANDB_API_KEY}

target:
  service: sing
  name: whitney02
  workspace_name: sfm-ws

environment:
  image: ai4s-sfm/amd:20241111.140607-rocm624
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn
  setup:
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace

storage:
  eastus2:
    storage_account_name: sfmdatawestus # Storage account
    container_name: psm # Container name
    mount_dir: /psm

code:
  local_dir: ../../

jobs:
- name: psm-unified-20241216-1027
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS_PER_NODE}-MI300-IB@westus
  mpi: true
  identity: user
  process_count_per_node: 1
  command:
  - export data_path=/psm/data/
  - mkdir -p /psm/sfmexpresults/shiyu/psm-checkpoints/psm-unified-20241216-1027/
  - export save_dir=/psm/sfmexpresults/shiyu/psm-checkpoints/psm-unified-20241216-1027/
  - export sampled_structure_output_path=/psm/sfmexpresults/shiyu/psm-checkpoints/psm-unified-20241216-1027/
  - export pbc_cutoff=40.0
  - export pbc_expanded_num_cell_per_direction=5
  - export pbc_expanded_token_cutoff=512
  - export pbc_multigraph_cutoff=7.0
  - export pbc_use_local_attention=True
  - export use_no_pre_cutoff_softmax=True

  - export backbone=seq-dit-geom
  - export layers=14
  - export hidden_size=1536
  - export ffn_size=6144
  - export num_structure_encoder_layer=12
  - export structure_ffn_dim=1536
  - export structure_hidden_dim=1536
  - export num_pred_attn_layer=4
  - export decoder_hidden_dim=1536
  - export decoder_ffn_dim=1536
  - export num_head=32
  - export max_length=384
  - export max_residue_num=384

  # - export data_path_list='PubChemQC-B3LYP-PM6,AFDB70-plddt70-reduce.lmdb,matter-sim-15M-merged,20240630_PDB_Training_Data,matter-gen-force-filtered,ESM_ATLAS_reduce.lmdb'
  # - export dataset_name_list='pm6-wb97xd3,esm,mattersim,pdb,mattersim,esm'
  # - export dataset_split_raito='0.2,0.25,0.3,0.05,0.1,0.1'
  # - export dataset_micro_batch_size="12,8,4,8,12,8"

  # - export data_path_list='AFDB70-plddt70-reduce.lmdb'
  # - export dataset_name_list='esm'
  # - export dataset_split_raito='1.0'
  # - export dataset_micro_batch_size="8"

  - export data_path_list='PubChemQC-B3LYP-PM6,matter-sim-15M-correct-stress,MGnify,UniProt-updated-plddt70-reduce.lmdb,AFDB90-plddt70-reduce.lmdb,20240630_PDB_Training_Data'
  - export dataset_name_list='pm6-wb97xd3,mattersim,mgnify,esm,esm,pdbcomplexmultimer'
  - export dataset_split_raito='0.2,0.3,0.1,0.1,0.2,0.1'
  - export dataset_micro_batch_size="12,6,16,16,16,16"

  - export save_batch_interval=2500
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export gradient_accumulation_steps=2
  - export val_batch_interval=0

  - export wandb_project=psm_dev_shiyu_unified_20241119
  - export wandb_group=psm_dev_shiyu_20241015
  - export WANDB_RUN_NAME=psm_unified_continue_mat_edmprot

  - export total_num_steps=4000000
  - export warmup_num_steps=24000
  - export max_lr=1e-4

  - export diffusion_mode="edm"
  - export diffusion_noise_std=1.0
  - export edm_diffusion_noise_std=1.0
  - export equivar_vec_init=RELATIVE_POS_VEC_BIAS
  - export strategy=Zero1
  - export fp16=False
  - export clean_sample_ratio=0.5
  - export mode_prob='0.0,1.0,0.0'
  - export complex_mode_prob='1.0,0.0,0.0,0.0'
  - export mask_ratio=0.0

  - export use_graphormer_path_edge_feature=False
  - export use_ddpm_for_material=True
  - export diff_init_lattice_size=10.0
  - export wrap_in_periodic_diffusion=False
  - export recompute_noise_after_wrap=False
  - export periodic_lattice_diffusion_noise_std=0.5
  - export diffusion_sampling="ddpm"
  - export num_timesteps=5000
  - export ddpm_beta_start=1e-7
  - export ddpm_beta_end=2e-3
  - export ddpm_schedule=sigmoid
  - export loadcheck_path='/psm/sfmexpresults/shiyu/psm-checkpoints/psm-unified-20241201-1848/global_step67500/mp_rank_00_model_states.pt'
  - export psm_finetune_mode=False
  - export psm_validation_mode=False
  - export sample_in_validation=False
  - export psm_finetune_reset_head=False
  - export mm_tensorcore=fp32

  - export equivar_use_linear_bias=True
  - export equivar_use_attention_bias=True

  - export use_unified_batch_sampler=True
  - export rescale_loss_with_std=True
  - export only_use_rotary_embedding_for_protein=True
  - export use_memory_efficient_attention=False
  - export unified_data_num_workers=4
  - export use_fp32_in_decoder=False
  - export material_force_loss_ratio=1.0
  - export material_energy_loss_ratio=1.0
  - export molecule_energy_loss_ratio=1.0
  - export energy_per_atom_label_scale=1.0
  - export mlm_from_decoder_feature=True
  - export num_3d_bias_kernel=32

  - export diffusion_training_loss=L2

  - export use_protein_relative_pos=False
  - export use_protein_rotary_embedding=True
  - export num_protein_relative_pos_bin=32
  - export share_attention_bias=True
  - export attention_bias_in_decoder=True

  - export molecule_ref_energy_source='PubChemQC-B3LYP-PM6/wb97xd3/1.0.0/train'
  - export molecule_outlier_energy_atoms=''

  - export use_fixed_init_lattice_size=False
  - export diff_init_lattice_size=10.0
  - export diff_init_lattice_size_factor=2.859496852322873
  - export periodic_lattice_diffusion_noise_std=0.5
  - export use_adaptive_noise_std_for_periodic=True
  - export periodic_diffusion_noise_std_factor=1.0531306506190654
  - export supervise_prediction_stress=False
  - export supervise_autograd_stress=True
  - export stress_loss_factor=0.1

  - export separate_noise_head=True
  - export if_total_energy=False

  - export AutoGradForce=True
  - export supervise_force_from_head_when_autograd=True
  - export n_gpu=${GPUS_PER_NODE}

  - export wandb_run_name="continue_v0_training"

  - export log_interval=100

  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - bash ./scripts/psm/get_azcopy.sh
  - mkdir -p /tmp/psmdata/PubChemQC-B3LYP-PM6
  - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/PubChemQC-B3LYP-PM6/wb97xd3/<SAS>" bash ./scripts/psm/azcopydata.sh
  - mv /tmp/psmdata/wb97xd3 /tmp/psmdata/PubChemQC-B3LYP-PM6/
  - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/AFDB90-plddt70-reduce.lmdb/<SAS>" bash ./scripts/psm/azcopydata.sh
  - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/UniProt-updated-plddt70-reduce.lmdb/<SAS>" bash ./scripts/psm/azcopydata.sh
  - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/20240630_PDB_Training_Data/<SAS>" bash ./scripts/psm/azcopydata.sh
  - mkdir -p /tmp/psmdata/MGnify
  - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/MGnify/mgnify90_2019_05.cluster_size_gt1.sequence_length_20to2699.20211129_c8e25fe8.plddt_gt70.lmdb/<SAS>" bash ./scripts/psm/azcopydata.sh
  - mv /tmp/psmdata/mgnify90_2019_05.cluster_size_gt1.sequence_length_20to2699.20211129_c8e25fe8.plddt_gt70.lmdb /tmp/psmdata/MGnify
  - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/matter-sim-15M-correct-stress/<SAS>" bash ./scripts/psm/azcopydata.sh
  # - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/AFDB70-plddt70-reduce.lmdb/<SAS>" bash ./scripts/psm/azcopydata.sh
  # - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/matter-sim-15M-merged/<SAS>" bash ./scripts/psm/azcopydata.sh
  # - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/matter-gen-force-filtered/<SAS>" bash ./scripts/psm/azcopydata.sh
  # - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/mattersim-30M-less200-filtered-merged/<SAS>" bash ./scripts/psm/azcopydata.sh
  # - train_data_sas="https://sfmdatawestusprem.blob.core.windows.net/psm/data/oc20-s2ef/<SAS>" bash ./scripts/psm/azcopydata.sh
  - bash ./scripts/psm/pretrain_psm.sh
  submit_args:
    env:
      SHARED_MEMORY_PERCENT: 0.9
      AMLT_DOCKERFILE_TEMPLATE: "none"
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/3eaeebff-de6e-4e20-9473-24de9ca067dc/resourceGroups/sfm-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/sfm-job-identity
  sla_tier: Premium
