# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# train a chemical generalist

description: psm

env_defaults:
  NODES: 8
  GPUS_PER_NODE: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

target:
  service: sing
  name: baltic02
  workspace_name: sfm-ws

environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
  eastus2:
    storage_account_name: sfmdataeastus2 # Storage account
    container_name: psm # Container name
    mount_dir: /psm
  arca100:
    storage_account_name: sfmarca100 # Storage account
    container_name: sfm # Container name
    mount_dir: /sfm

code:
  local_dir: ../../

jobs:
- name: psm-molecule-protein-periodic-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-test-diffnoise10-fastpreprocess-20240725-1050
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS_PER_NODE}-IB
  mpi: true
  identity: managed
  process_count_per_node: 1
  command:
  - export data_path=/psm/data/
  - mkdir -p /sfm/sfmexpresults/shiyu/psm-checkpoints/pubchem-pm6-diffusion-molecule-protein-periodic-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-unified-sampler-continued-fastpreprocess-20240725-1050
  - export save_dir=/sfm/sfmexpresults/shiyu/psm-checkpoints/pubchem-pm6-diffusion-molecule-protein-periodic-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-unified-sampler-continued-fastpreprocess-20240725-1050
  - export pbc_cutoff=20.0
  - export pbc_expanded_num_cell_per_direction=5
  - export pbc_expanded_token_cutoff=256
  - export pbc_multigraph_cutoff=5.0
  - export pbc_use_local_attention=True

  - export layers=24
  - export hidden_size=1536
  - export ffn_size=6144
  - export decoder_ffn_dim=6144
  - export num_head=32
  - export max_length=512
  - export num_pred_attn_layer=4

  - export data_path_list='PubChemQC-B3LYP-PM6,matter-sim-15M-force-filtered-merged,AFDB70-plddt70.lmdb,matter-sim-15M-merged,ur50_23_bpe_pack512.lmdb,20240630_PDB_Training_Data,20240630_PDB_Training_Data,matter-gen-force-filtered'
  - export dataset_name_list='pm6,mattersim,afdb,mattersim,ur50,pdb,pdbcomplexmultimer,mattersim'
  - export dataset_split_raito='0.2,0.025,0.35,0.2,0.1,0.05,0.05,0.025'
  - export dataset_micro_batch_size="12,4,3,4,3,3,3,4"

  - export save_batch_interval=2500
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export gradient_accumulation_steps=8
  - export val_batch_interval=0

  - export wandb_project=psm_dev_shiyu_20240719
  - export wandb_group=psm_dev_shiyu_20240719
  - export WANDB_RUN_NAME=psm-mol-pro-periodic-diff-relpos-noise1-relativepos-diffnoise10-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-unified-sampler-fastpreprocess-20240725-1050

  - export total_num_steps=4000000
  - export warmup_num_steps=24000
  - export max_lr=2e-4

  - export diffusion_noise_std=10.0
  - export equivar_vec_init=RELATIVE_POS_VEC_BIAS
  - export strategy=DDP
  - export fp16=False
  - export clean_sample_ratio=0.5
  - export mode_prob='0.4,0.5,0.1'

  - export diff_init_lattice_size=10.0
  - export diffusion_sampling="ddpm"
  - export num_timesteps=5000
  - export ddpm_beta_start=1e-7
  - export ddpm_beta_end=2e-3
  - export ddpm_schedule=sigmoid

  - export equivar_use_linear_bias=True
  - export equivar_use_attention_bias=True

  - export use_unified_batch_sampler=True
  - export rescale_loss_with_std=True
  - export only_use_rotary_embedding_for_protein=True
  - export use_memory_efficient_attention=False
  - export unified_data_num_workers=4
  - export use_fp32_in_decoder=False
  - export material_force_loss_ratio=1.0
  - export material_energy_loss_ratio=1.0
  - export molecule_energy_loss_ratio=1.0
  - export energy_per_atom_label_scale=1.0
  - export mlm_from_decoder_feature=True

  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install nvidia-dali-cuda120
  - bash ./scripts/psm/pretrain_psm.sh
  submit_args:
    container_args:
      shm_size: 1024g
  preemptible: false
