# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# train a chemical generalist

description: PSMV1-VT-V8-consis

env_defaults:
  NODES: 8 # LOCAL
  GPUS_PER_NODE: 8

target:
    service: aml
    name: townsend1

environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io # msroctocr.azurecr.io
  username: msrmoldyn

storage:
  blob:
    storage_account_name: sfmarca100 # Storage account
    container_name: sfm # Container name
    mount_dir: /blob

code:
  local_dir: . # LOCAL

jobs:
- name: psmv1_vt_v8-consis-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-test-diffnoise10-fastpreprocess-20240622 # LOCAL
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS_PER_NODE}-IB
  mpi: true
  process_count_per_node: 1
  identity: managed # Do not use this when submitting to `sing`
  command:
  - export data_path=/nfs/psmdata/
  - mkdir -p /blob/sfmexpresults/chang/psmv1_vt_v8-consis-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-test-diffnoise10-fastpreprocess-20240622 # LOCAL
  - export save_dir=/blob/sfmexpresults/chang/psmv1_vt_v8-consis-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-test-diffnoise10-fastpreprocess-20240622 # LOCAL
  - export loadcheck_path=/blob/sfmexpresults/peiran/psmv1_vt_v8/checkpoints/global_step389895/mp_rank_00_model_states.pt # /blob/sfmexpresults/peiran/psmv1_vt_v8/checkpoints/global_step344025/mp_rank_00_model_states.pt # LOCAL
    # LOCAL
    # - export pbc_cutoff=20.0
    # - export pbc_expanded_num_cell_per_direction=5
    # - export pbc_expanded_token_cutoff=256
    # - export pbc_multigraph_cutoff=5.0
    # - export pbc_use_local_attention=False

  - export num_pred_attn_layer=4
  - export layers=22
  - export hidden_size=1024
  - export ffn_size=4096
  - export num_head=32
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.0
  - export attn_dropout=0.1
  - export act_dropout=0.1
  - export droppath_prob=0.0
  - export mask_ratio=0.5

  # - export save_batch_interval=2500
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export gradient_accumulation_steps=4
  - export log_interval=100
  - export max_tokens=16000
  - export max_length=512
  # - export val_batch_interval=0

  - export WANDB_KEY="local-85345c4f912e9a70ed217696c982f6e2b2b86b3e" # LOCAL
  - export WANDB_GROUP=psm_dev_vt
  - export WANDB_PROJECT="eng-struct-consis" # LOCAL
  - export WANDB_RUN_NAME=psmv1_vt_v8-consis-${NODES}xG${GPUS_PER_NODE}-fp32-ddp-test-diffnoise10-fastpreprocess-20240622 # LOCAL

  - export pipeline_model_parallel_size=0
  - export total_num_steps=500000 # LOCAL
  - export warmup_num_steps=20000 # LOCAL
  - export weight_decay=0.0
  - export d_tilde=1.0
  - export max_lr=1.0e-4 # LOCAL 2e-4

  - export diffusion_noise_std=10.0
  - export equivar_vec_init=RELATIVE_POS # LOCAL ZERO_CENTERED_POS
  - export strategy=Zero1 # Zero1 # LOCAL DDP
  - export fp16=False
  - export clean_sample_ratio=0.5
  - export mode_prob=0.1,0.2,0.7

  - export diff_init_lattice_size=10.0
  - export diffusion_sampling="ode" # Preferred
  - export num_timesteps=1000 # Preferred; required by LOCAL
  - export ddpm_beta_start=1e-4 # Preferred
  - export ddpm_beta_end=2e-2 # Preferred
  - export ddpm_schedule=sigmoid

  # LOCAL
  # - export equivar_use_linear_bias=True
  # - export equivar_use_attention_bias=True

  - export data_path_list='PubChemQC-B3LYP-PM6,matter-sim-15M-force-filtered-merged,AFDB50-plddt70.lmdb,matter-sim-15M-merged' # LOCAL "PubChemQC-B3LYP-PM6,matter-sim-15M-merged,AFDB50-plddt70.lmdb,matter-sim-15M-force-filtered-merged"
  - export dataset_name_list="pm6,mattersim,afdb,mattersim"
  - export dataset_split_raito="0.4,0.1,0.4,0.1"
  - export dataset_micro_batch_size='32,5,6,5' # LOCAL "16,4,2,4"
  - export use_unified_batch_sampler=True
  - export use_dali_pipeline=False
  - export rescale_loss_with_std=False # LOCAL
  - export energy_loss_ratio=0.1 # LOCAL 1.0
  - export force_loss_ratio=0.5 # LOCAL 1.0
  - export diffusion_loss_ratio=0.1 # LOCAL 1.0
  - export aa_mlm_loss_ratio=1.0
  # LOCAL
  # - export only_use_rotary_embedding_for_protein=False
  - export use_memory_efficient_attention=True

  # LOCAL
  - export psm_finetune_mode=True
  - export psm_finetune_reset_head=False
  - export psm_finetune_noise_mode="diffusion"
  - export psm_finetune_valid_noise_mode="diffusion"

  - export cons_molecules_only=True

  - export use_score_consistency=True # LOCAL
  - export score_cons_time_step_low=5
  - export score_cons_time_step_high=300
  - export score_cons_energy_temperature=0.1
  - export score_cons_coeff=10.0

  - export use_optim_consistency=False
  - export optim_cons_time_step_low=400
  - export optim_cons_time_step_high=700
  - export optim_cons_coeff=1.0
  - export optim_cons_perturb_std_max=0.1

  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install nvidia-dali-cuda120
  - bash ./scripts/psm/pretrain_psm_vanillatransformer.sh # LOCAL ./scripts/psm/pretrain_psm.sh
  submit_args:
    container_args:
      shm_size: 1024g
  preemptible: false
