 # Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV0

env_defaults:
  NODES: 4
  GPUS: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

# target:
#     service: sing
#     name: baltic02

target:
    service: aml
    name: townsend1
    # name: sfm-nd96amsra100v4-uksouth
#     # name: sfm-nc96-westus3

environment:
  # image: yaosen/sfm-py39-torch2.2.2-cuda12.1:20240417_a
  image: ai4s-sfm:20240429.081857
  registry: msroctocr.azurecr.io
  username: msroctocr

storage:
  blob:
    storage_account_name: hai1data # Storage account
    container_name: sfm # Container name
    mount_dir: /blob

code:
  local_dir: ../SFM_framework

jobs:
- name: psmV1_VT_v0
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS}
  mpi: true
  process_count_per_node: 1
  command:
  - export WANDB_TEAM=ai4s-sfm
  - export wandb_group=psm_VT_001
  - export wandb_project=psm_VT
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - mkdir /blob/pfmexp/output
  - mkdir /blob/experiment/psm/psmV1_VT_v0
  - mkdir /blob/experiment/psm/psmV1_VT_v0/checkpoints
  - mkdir ./output
  - export path=run.sh
  - export num_pred_attn_layer=4
  - export layers=12
  - export hidden_size=1024
  - export ffn_size=4096
  - export num_head=32
  - export num_3d_bias_kernel=8
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.0
  - export attn_dropout=0.1
  - export act_dropout=0.1
  - export weight_decay=0.0
  - export droppath_prob=0.0
  - export mask_ratio=0.5
  - export d_tilde=1.0
  - export max_lr=1e-4
  - export strategy=Zero1
  - export pipeline_model_parallel_size=0
  - export total_num_steps=2000000
  - export warmup_num_steps=1000
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export max_tokens=16000
  - export max_length=512
  - export gradient_accumulation_steps=1
  - export log_interval=100
  - export data_path=/blob/psm/
  - export data_path_list='PubChemQC-B3LYP-PM6,matter-sim-3M,AFDB50-plddt70.lmdb'
  - export dataset_name_list='pm6,mattersim,afdb'
  - export dataset_split_raito='0.5,0.0,0.5'
  - export dataset_micro_batch_size='256,32,32'
  - export loadcheck_path=/blob/experiment/psm/psmV1_VT_v0/checkpoints
  - export save_dir=/blob/pfmexp/output/psmV1_VT_v0/checkpoints
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - bash ./scripts/psm/pretrain_psm_vanillatransformer.sh
  submit_args:
    container_args:
      shm_size: 1024g
