 # Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV1

env_defaults:
  NODES: 16
  GPUS: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

target:
  service: sing
  name: whitney02
  # name: msroctobasicvc
  workspace_name: sfm-ws

environment:
  image: ai4s-sfm/amd:20241022.151209
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn
  setup:
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace

storage:
  # blob:
  #   storage_account_name: sfmarca100 # Storage account
  #   container_name: sfm # Container name
  #   mount_dir: /sfm
  blob:
    storage_account_name: sfmdatawestus # Storage account
    container_name: psm # Container name
    mount_dir: /blob
  westus:
    storage_account_name: sfmdatawestusprem # Storage account
    container_name: psm # Container name
    mount_dir: /psm

code:
  local_dir: ../SFM_framework

jobs:
- name: psmv1_dit_v20_1b_stage1
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS}-MI300@westus
  mpi: true
  identity: managed
  process_count_per_node: 1
  command:
  - export WANDB_TEAM=ai4s-sfm
  - export wandb_group=psm_exp_v22
  - export wandb_project=psm_VT
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export HSA_ENABLE_SDMA=0
  - export NCCL_IB_PCI_RELAXED_ORDERING=1
  - export NCCL_NET_GDR_LEVEL=3
  - mkdir ./output
  - export path=run.sh
  - export backbone=exp3
  - export num_pred_attn_layer=16
  - export layers=32
  - export hidden_size=2048
  - export ffn_size=8192
  - export decoder_hidden_dim=2048
  - export decoder_ffn_dim=8192
  - export num_head=32
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.1
  - export attn_dropout=0.1
  - export act_dropout=0.1
  - export weight_decay=0.0
  - export droppath_prob=0.0
  - export mask_ratio=0.15
  - export mode_prob='0.1,0.9,0.0'
  - export complex_mode_prob='0.9,0.0,0.1,0.0'

  - export d_tilde=1.0
  - export max_lr=8e-5
  - export strategy=Zero1
  - export pipeline_model_parallel_size=0
  - export total_num_steps=200000
  - export warmup_num_steps=1000
  - export train_batch_size=2048
  - export val_batch_size=512
  - export max_tokens=16000
  - export max_length=768
  - export max_residue_num=768
  - export ligand_crop_size=20.0
  - export plddt_threshold=70.0
  - export gradient_accumulation_steps=8
  - export log_interval=100

  - export data_path=/psm/data/

  # - export data_path_list='UniProt90-UniRef50-updated-plddt70-reduce.lmdb' #,geom_drugs_full.lmdb'
  # - export dataset_name_list='esm' #,geom'
  # - export dataset_split_raito='1.0' #,0.2'
  # # - export dataset_micro_batch_size='16,16,16,16'
  # - export dataset_micro_batch_size='4'

  - export data_path_list='MGnify90-selected-plddt70-reduce.lmdb,UniProt90-UniRef50-updated-plddt70-reduce.lmdb,AFDB70-plddt70-reduce-updated.lmdb,20240630_PDB_Training_Data' #,geom_drugs_full.lmdb'
  - export dataset_name_list='esm,esm,esm,pdbcomplexmultimer' #,geom'
  - export dataset_split_raito='0.2,0.2,0.4,0.2' #,0.2'
  # - export dataset_micro_batch_size='16,16,16,16'
  - export dataset_micro_batch_size='4,4,4,4'

  - export fp16=False
  - export clean_sample_ratio=0.0
  - export diffusion_mode=edm
  - export diffusion_noise_std=1.0
  - export ddpm_schedule=sigmoid
  - export ddpm_beta_start=1e-7
  - export ddpm_beta_end=2e-3
  - export diffusion_training_loss=L2
  - export molecule_energy_loss_ratio=0.5
  - export molecule_force_loss_ratio=0.5
  - export material_energy_loss_ratio=0.5
  - export material_force_loss_ratio=0.5

  - export AutoGradForce=False
  - export use_hard_dist_loss=False
  - export use_unified_batch_sampler=True
  - export align_x0_in_diffusion_loss=True
  - export decoder_feat4energy=False
  - export encoderfeat4noise=False
  - export encoderfeat4mlm=True
  - export only_use_rotary_embedding_for_protein=True
  - export use_memory_efficient_attention=False
  - export if_total_energy=False
  - export save_batch_interval=2500
  - export loadcheck_path=/blob/sfmexpresults/peiran/psmv1_mi300_edm_exp3_v22_3b_ps_stage1_5c/checkpoints/global_step5000/mp_rank_00_model_states.pt
  - export psm_finetune_mode=False
  - export save_dir=/blob/sfmexpresults/peiran/psmv1_mi300_edm_exp3_v22_3b_ps_stage1_5c/checkpoints
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - bash ./scripts/psm/pretrain_psm_exp_amd.sh
  submit_args:
    env:
      AMLT_DOCKERFILE_TEMPLATE: "none"
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/3eaeebff-de6e-4e20-9473-24de9ca067dc/resourceGroups/sfm-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/sfm-job-identity
    container_args:
      shm_size: 1024G
  preemptible: false
