 # Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV0

env_defaults:
  NODES: 6
  GPUS_PER_NODE: 8
  WANDB_API_KEY: "local-065f023e262b3ae11107532ba5463cd2d800d739"

target:
  service: sing
  name: msroctovc
  workspace_name: sfm-ws

environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
    storageA:
      storage_account_name: sfmdataeastus2
      container_name: madft-nn
      mount_dir: /blob


code:
  local_dir: ../SFM_framework

jobs:
- name: e2former-pretrain-forcehead
  identity: managed
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}x40G${GPUS_PER_NODE}-A100-IB
  sla_tier: Premium
  priority: High
  mpi: true
  process_count_per_node: 1
  command:
  - export OMPI_COMM_WORLD_SIZE=${NODES}
  - export HYDRA_FULL_ERROR=1
  - export load_ckpt=False
  - export MASTER_PORT=62352
#   mkdir /blob/pfmexp/output
#   mkdir /blob/experiment/psm/psmV0test_0507
#   mkdir /blob/experiment/psm/psmV0test_0507/checkpoints

  - export pbc_cutoff=20.0
  - export pbc_expanded_num_cell_per_direction=5
  - export pbc_expanded_token_cutoff=256
  - export pbc_multigraph_cutoff=5.0
  - export pbc_use_local_attention=False

  # e2former settings
  - export save_batch_interval=2500
  - export train_batch_size=16
  - export val_batch_size=16
  - export gradient_accumulation_steps=4
  - export val_batch_interval=0


  - export total_num_steps=200000000
  - export warmup_num_steps=1000
  - export max_lr=1.5e-4

  - export diffusion_noise_std=0
  - export strategy=DDP
  - export fp16=False
  - export clean_sample_ratio=1.0

  - export diff_init_lattice_size=10.0
  - export diffusion_sampling="ddpm"
  - export num_timesteps=5000
  - export ddpm_beta_start=1e-7
  - export ddpm_beta_end=2e-3
  - export ddpm_schedule=sigmoid

  - export equivar_use_linear_bias=True
  - export equivar_use_attention_bias=True

  - export use_unified_batch_sampler=True
  - export rescale_loss_with_std=True
  - export only_use_rotary_embedding_for_protein=True
  - export use_memory_efficient_attention=False

# Zhihao
  - export save_epoch_interval=20
  - export wandb_team=''
  - export wandb_group=psm_E2former_test
  - export wandb_project=psm_dev_stype
  - export WANDB_API_KEY="local-065f023e262b3ae11107532ba5463cd2d800d739"
  - export wandb_key="local-065f023e262b3ae11107532ba5463cd2d800d739"
  - export wandb_run_name="e2former-pretrain-forcehead"

  - export psm_finetune_mode=True

  - export data_path=/blob/dataset/
  # - export supervise_force_from_head_when_autograd=True

  - export data_path_list="GEMS/general_protein_fragments,deshaw/db_data_all_600"
  - export dataset_name_list='GEMS,deshaw'
  - export dataset_micro_batch_size="384,1"
  - export dataset_split_raito='0.1,0.9'

  - export loadcheck_path=$$AMLT_OUTPUT_DIR
  - export save_dir=$$AMLT_OUTPUT_DIR

  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - bash scripts/psm/finetune_psm_e2former.sh
  submit_args:
    env:
      AMLT_DOCKERFILE_TEMPLATE: "none"
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/3eaeebff-de6e-4e20-9473-24de9ca067dc/resourceGroups/sfm-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/sfm-job-identity
    container_args:
      shm_size: 1024g
