 # Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV0

env_defaults:
  NODES: 1
  GPUS_PER_NODE: 4
  WANDB_API_KEY: ""

target:
  service: aml
  name: es-madft-nc96-eastus2

environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
    storageA:
      storage_account_name: sfmdataeastus2 # Storage account
      container_name: psm # Container name
      mount_dir: /blob


code:
  local_dir: ../SFM_framework

jobs:
- name: e2former-Lin-afdb-15
  identity: managed
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: 80G4-A100
  priority: high
  command:
  - export HYDRA_FULL_ERROR=1
  - export load_ckpt=False
  - export MASTER_PORT=62352
  - export pbc_cutoff=20.0
  - export pbc_expanded_num_cell_per_direction=5
  - export pbc_expanded_token_cutoff=256
  - export pbc_multigraph_cutoff=5.0



  - export gradient_accumulation_steps=4


  - export total_num_steps=200000000
  - export warmup_num_steps=12000
  - export max_lr=1.5e-4

  - export equivar_vec_init=ZERO_CENTERED_POS
  - export strategy=DDP
  - export fp16=False

  - export diff_init_lattice_size=10.0
  - export diffusion_sampling="ddpm"
  - export num_timesteps=5000
  - export ddpm_beta_start=1e-7
  - export ddpm_beta_end=2e-3
  - export ddpm_schedule=sigmoid

  - export equivar_use_linear_bias=True
  - export equivar_use_attention_bias=True

  - export dataset_micro_batch_size="4"
  - export use_unified_batch_sampler=True
  - export rescale_loss_with_std=True
  - export only_use_rotary_embedding_for_protein=True
  - export use_memory_efficient_attention=False

  - export data_path=/blob/
  - export data_path_list="data/AFDB70-plddt70.lmdb" #"psm/data/matter-sim-15M-force-filtered-merged"
  - ls /blob
  - export dataset_name_list='afdb'
  - export dataset_split_raito='1.0'

  - export ifresume=True
  - export loadcheck_path=$$AMLT_OUTPUT_DIR
  - export save_dir=$$AMLT_OUTPUT_DIR

  - export wandb_group='Lin_psm_dev_afdb'
  # - export save_dir='/blob/'
  # - mkdir -p /blob/psm-checkpoints
  # - mkdir -p /blob/psm-checkpoints/EQV2-oc20+SPICE(100k+400k)-06-29
  # -   - export save_dir=/blob/psm-checkpoints/EQV2-oc20+SPICE(100k+400k)-06-29
  - df -hl
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install nvidia-dali-cuda120
  - bash scripts/psm/pretrain_localafdb_1.sh
  submit_args:
    container_args:
      shm_size: 512g
