# Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV1_EVALPROT

env_defaults:
  NODES: 1
  GPUS: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

target:
  service: aml
  name: townsend1

environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
  sfm:
    storage_account_name: sfmarca100 # Storage account
    container_name: sfm # Container name
    mount_dir: /sfm
  # psm:
  #   storage_account_name: sfmdataeastus2 # Storage account
  #   container_name: psm # Container name
  #   mount_dir: /psm

code:
  local_dir: $CONFIG_DIR/../../../

jobs:
- name: psmv1_vt_v10_1b_stage1_evalprot
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS}-IB
  mpi: true
  process_count_per_node: 1
  identity: managed
  command:
  - export WANDB_TEAM=ai4s-sfm
  - export wandb_group=psm_VT
  - export wandb_project=psm_VT
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - mkdir /blob/pfmexp/output
  - mkdir /blob/experiment/psm/psmv1_vt_v10_1b
  - mkdir /blob/experiment/psm/psmv1_vt_v10_1b/checkpoints
  - mkdir ./output
  - export path=run.sh
  - export num_pred_attn_layer=4
  - export layers=32
  - export hidden_size=1536
  - export ffn_size=6144
  - export num_head=32
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.0
  - export attn_dropout=0.1
  - export act_dropout=0.1
  - export weight_decay=0.0
  - export droppath_prob=0.0
  - export mask_ratio=0.5
  - export d_tilde=1.0
  - export max_lr=1.5e-4
  - export strategy=Zero1
  - export pipeline_model_parallel_size=0
  - export total_num_steps=500000
  - export warmup_num_steps=20000
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export max_tokens=16000
  - export max_length=512
  - export gradient_accumulation_steps=8
  - export log_interval=100
  - export data_path=/nfs6/psmdata/
  # - export data_path=/psm/data/
  - export data_path_list='PubChemQC-B3LYP-PM6,matter-sim-15M-force-filtered-merged,AFDB70-plddt70.lmdb,matter-sim-15M-merged,ur50_23_bpe_pack1536.lmdb'
  - export dataset_name_list='pm6,mattersim,afdb,mattersim,ur50'
  - export dataset_split_raito='0.2,0.1,0.4,0.1,0.2'
  - export dataset_micro_batch_size='64,8,8,8,8'
  - export mode_prob='0.4,0.4,0.2'
  - export fp16=False
  - export clean_sample_ratio=0.5
  - export energy_loss_ratio=0.001
  - export force_loss_ratio=0.0
  # - export num_timesteps=1000
  # - export ddpm_beta_start=1e-4
  # - export ddpm_beta_end=2e-2
  - export use_unified_batch_sampler=True
  - export use_dali_pipeline=False
  - export save_batch_interval=30000
  - export loadcheck_path=/sfm/sfmexpresults/peiran/psmv1_vt_v10_1b/checkpoints
  - export save_dir=/sfm/sfmexpresults/peiran/psmv1_vt_v10_1b/checkpoints
  # - export loadcheck_path=/psm/exp/peiran/psmv1_vt_v5/checkpoints
  # - export save_dir=/psm/exp/peiran/psmv1_vt_v5/checkpoints
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - pip install nvidia-dali-cuda120
  - export mask_ratio=0.0
  - export mode_prob='0.0,1.0,0.0'
  - export max_length=2048
  - export psm_validation_mode=True
  - export data_path="/sfm/psm/cameo-subset-casp14-and-casp15-combined.lmdb"
  - export loadcheck_path="/sfm/sfmexpresults/peiran/psmv1_vt_v10_1b/checkpoints/global_step160000/mp_rank_00_model_states.pt"
  - export save_dir="/sfm/sfmexpresults/jianwei/psmv1_vt_v10_1b/checkpoints/global_step160000/prediction"
  - inpsh="./scripts/psm/pretrain_psm_vanillatransformer.sh"
  - outsh="./scripts/psm/evaluate_psm_vanillatransformer_protein.sh"
  - cp $$inpsh $$outsh
  - sed -i 's/pretrain_psm.py/evaluate_psm_protein.py/' $$outsh
  - sed -i 's/seed=12345/seed=12345 max_model_num=1/' $$outsh
  - mkdir -p $$save_dir
  - bash $$outsh && rm $$outsh
  submit_args:
    container_args:
      shm_size: 1024g
  preemptible: false
