 # Steps to run:
# 1. copy data folder https://itpeus4data.blob.core.windows.net/shuz/data/pcq-pos-custom/ to your Azure storage blob container
# 2. copy script mae_3d.sh in FoundationModelProp/ to your Azure storage blob container
# 3. Specify the Azure storage account and container to use
# 4. Submit the job with this yaml file

description: PSMV1

env_defaults:
  NODES: 8
  GPUS: 8
  WANDB_API_KEY: "local-094f941ede8eda7a00c307f50595f054be5382f7"

target:
  service: aml
  name: townsend1

environment:
  image: ai4s-sfm:20240531.170731
  registry: msrmoldyn.azurecr.io
  username: msrmoldyn

storage:
  blob:
    storage_account_name: sfmarca100 # Storage account
    container_name: sfm # Container name
    mount_dir: /sfm

code:
  local_dir: ../SFM_framework

jobs:
- name: psmv1_vt_v10_stage0
  tags: [Project_Name:Science_Foundation_Model,ProjectID:PRJ-0209-A40,Experiment:SFM_PSM]
  sku: ${NODES}xG${GPUS}-IB
  mpi: true
  process_count_per_node: 1
  command:
  - export WANDB_TEAM=ai4s-sfm
  - export wandb_group=psm_VT_stage0
  - export wandb_project=psm_VT
  - export WANDB_API_KEY=${WANDB_API_KEY}
  - export layers=32
  - export hidden_size=1536
  - export ffn_size=6144
  - export num_head=32
  - export atom_loss_coeff=1.0
  - export pos_loss_coeff=1.0
  - export sandwich_ln="true"
  - export dropout=0.1
  - export attn_dropout=0.1
  - export act_dropout=0.0
  - export weight_decay=0.0
  - export droppath_prob=0.0
  - export max_num_aa=1024
  - export noise_mode=diff
  - export noise_scale=0.2
  - export mask_prob=0.20
  - export mode_prob=1.0,0.0,0.0
  - export d_tilde=1.0
  - export max_lr=4e-5
  - export strategy=DDP
  - export pipeline_model_parallel_size=0
  - export total_num_steps=600000
  - export warmup_num_steps=30000
  - export train_batch_size=1024
  - export val_batch_size=1024
  - export max_tokens=3072
  - export max_length=1536
  - export gradient_accumulation_steps=1
  - export log_interval=100
  - export wandb_group=BFM
  - export wandb_project=ds_mfmpre
  - export loadcheck_path=/psm/exp/peiran/psmv1_vt_v10_stage0/checkpoints
  - export save_dir=/psm/exp/peiran/psmv1_vt_v10_stage0/checkpoints
  - export train_data_path=/mnt/amlt_code/ur50_23_bpe_pack1536.lmdb/
  - export valid_data_path=/mnt/amlt_code/uniref50_valid.lmdb/
  - bash ./scripts/pfm/copy_from_nfs.sh
  - export save_dir=/blob/pfmexp/output/psmv1_vt_v10_stage0/checkpoints
  - eval "$$(conda shell.bash hook)" && conda activate sfm
  - python setup_cython.py build_ext --inplace
  - bash ./scripts/pfm/pretrain_pfm.sh
  submit_args:
    container_args:
      shm_size: 1024g
